Feature: QR Code Scanning Integration
YassinNouh21/event_plus pull request #1
Opened 2023-10-08 11:05 UTC by YassinNouh21

## Description
This pull request adds a QR code scanning feature to our application, allowing users to easily scan QR codes for various purposes. it can be used in different features like registeration and sign up users in the event

## Type of Change

- [ X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-10-08 16:32 UTC, 3bdelrahmann requested changes

2023-10-09 10:49 UTC, YassinNouh21 commented on lib/feature/qr_code_scan/application/qr_code_scanner_bloc.dart
> +  Future _startScanning(
sure

2023-10-09 11:02 UTC, YassinNouh21 commented
@3bdelrahmann  I solved all the reivews

2023-10-09 12:29 UTC, 3bdelrahmann approved these changes

2023-10-09 12:30 UTC, merged